version: "3.5"

services: &services
  api01: &api
    hostname: api01
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: release
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "185MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3001:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "17MB"

  db: &db
    image: postgres:latest
    hostname: db
    command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    healthcheck:
      interval: 3s
      test: pg_isready -U admin -d rinha
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "133MB"
    volumes:
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1